#
# SonarQube analysis configuration
#
sonar.host.url=http://localhost:9000
sonar.projectKey=LeAF-CI4
sonar.projectName=LeAF-CI4
sonar.token=sqp_6d7c4e8836805e243618e298792cad01eef26f9b

sonar.language=php
sonar.sources=app
sonar.tests=tests
sonar.projectVersion=0.1
sonar.sourceEncoding=UTF-8
sonar.exclusions=vendor/**/*.*, writable/**/*.*, public/addons/**/*.*, public/fonts/**/*.*
