<?php
$releases = [
  //---------------------------------------------------------------------------
  [
    'version' => '5.0.0',
    'date' => '2024-11-02',
    'info' => 'This is a new major release of LeAF based on CodeIgniter 4:',
    'bugfixes' => [],
    'features' => [
      [ 'summary' => 'Lightbox2 replaces Magnific Popup', 'issue' => '' ],
      [ 'summary' => 'Highlight.js replaces Syntaxhighlighter', 'issue' => '' ],
      [ 'summary' => 'Sample page', 'issue' => '' ],
      [ 'summary' => 'Bootstrap 5 Library', 'issue' => '' ],
      [ 'summary' => 'Dark mode / Light mode', 'issue' => '' ],
      [ 'summary' => 'Navbar / Sidebar', 'issue' => '' ],
    ],
    'improvements' => [
      [ 'summary' => 'PHP 8.2+ adjustments', 'issue' => '' ],
      [ 'summary' => 'SonarQube code quality changes', 'issue' => '' ],
    ],
    'removals' => [
      [ 'summary' => 'Removed CKEditor (annoying and not secure enough)', 'issue' => '' ],
    ],
  ],
];
?>
<!-- Release Info -->
<ul class="timeline">
  <?php foreach ($releases as $release) { ?>
    <li>
      <div class="card mb-3">
        <div class="card-header"><i class="bi bi-box bi-lg me-3"></i>Release <?= $release['version'] ?><span class="float-end"><i class="bi bi-calendar bi-lg me-3"></i><?= $release['date'] ?></span></div>
        <div class="card-body">

          <?php if (strlen($release['info'])) { ?>
            <p><?= $release['info'] ?></p>
          <?php } ?>

          <?php if (count($release['bugfixes'])) { ?>
            <h6><?= lang('App.about.bugfixes') ?></h6>
            <ul>
              <?php foreach ($release['bugfixes'] as $bugfix) { ?>
                <li><?= $bugfix['summary'] ?><?= (strlen($bugfix['issue']) ? ' ( <a href="' . $bugfix['issue'] . '" target="_blank"><i class="bi bi-box-arrow-up-right me-1"></i>Issue</a> )' : '') ?></li>
              <?php } ?>
            </ul>
          <?php } ?>

          <?php if (count($release['improvements'])) { ?>
            <h6><?= lang('App.about.improvements') ?></h6>
            <ul>
              <?php foreach ($release['improvements'] as $improvement) { ?>
                <li><?= $improvement['summary'] ?><?= (strlen($improvement['issue']) ? ' ( <a href="' . $improvement['issue'] . '" target="_blank"><i class="bi-box-arrow-up-right me-1"></i>Issue</a> )' : '') ?></li>
              <?php } ?>
            </ul>
          <?php } ?>

          <?php if (count($release['features'])) { ?>
            <h6><?= lang('App.about.newFeatures') ?></h6>
            <ul>
              <?php foreach ($release['features'] as $feature) { ?>
                <li><?= $feature['summary'] ?><?= (strlen($feature['issue']) ? ' ( <a href="' . $feature['issue'] . '" target="_blank"><i class="bi-box-arrow-up-right me-1"></i>Issue</a> )' : '') ?></li>
              <?php } ?>
            </ul>
          <?php } ?>

          <?php if (count($release['removals'])) { ?>
            <h6><?= lang('App.about.removals') ?></h6>
            <ul>
              <?php foreach ($release['removals'] as $removal) { ?>
                <li><?= $removal['summary'] ?><?= (strlen($removal['issue']) ? ' ( <a href="' . $removal['issue'] . '" target="_blank"><i class="bi-box-arrow-up-right me-1"></i>Issue</a> )' : '') ?></li>
              <?php } ?>
            </ul>
          <?php } ?>

        </div>
      </div>
    </li>
  <?php } ?>
</ul>
